REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM miguel;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM miguel;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM miguel;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM miguel;
DROP USER miguel;
